services:
  api:
    build: ./wavely-backend
    ports:
      - '5000:5000'
    env_file:
      - ./wavely-backend/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  web:
    build:
      context: ./wavely-frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000/api/v1
    ports:
      - '3000:3000'
    depends_on:
      - api
    restart: unless-stopped
